name = "CFHydrostatics"
uuid = "0dc8c93d-0116-402a-b00b-85ddfe5501a2"
authors = ["The ClimFlows contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
